apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-replicaaset

spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  # pods =>
  template:
    metadata:
      name: app_nginx
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 8080
